# Generated by Django 6.0 on 2025-12-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('presentation', models.CharField(blank=True, max_length=255)),
                ('adult_dose', models.TextField(blank=True)),
                ('pediatric_dose', models.TextField(blank=True)),
                ('is_pediatric', models.BooleanField(default=False)),
                ('max_dose', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255)),
                ('warnings', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('cat_liver', models.CharField(blank=True, max_length=255)),
                ('cat_kidney', models.CharField(blank=True, max_length=255)),
                ('cat_lactation', models.CharField(blank=True, max_length=255)),
                ('cat_pregnancy', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
